### ISSUE TITLE
can this tool deauth a whole wifi?

### ISSUE THREAD

**Issue by ssjblue-xxx** [DustinBorn/CDeauth#1]

**Comment by ssjblue-xxx** [comment]
really dumb question

**Comment by ra1nb0rn** [comment]
Hi, the tool does not provide a built-in functionality for this. However, it might be possible to conduct the deauthentication of all clients by using the Broadcast MAC address (``FF:FF:FF:FF:FF:FF``) as client MAC address in the tool (``-c``). Since I don't have a setup for this currently, you would need to try this for yourself. If you do, you're welcome to post your results here ;)

**Comment by ssjblue-xxx** [comment]
ok, another dumb question. how do i get the Broadcast MAC address? i am kinda new at deauthing

**Comment by ra1nb0rn** [comment]
It's okay if you're new at it. If you don't know the answer to that question though, you probably shouldn't be using this tool yet. You will find your answer when learning the basic fundamentals of layer 2 networking.

As this is no longer a problem or question related to the tool, I'm closing this issue.

**Comment by 4lpndev** [comment]
hello! this is my second acc i lost access to the first one (ssjblue-xxx).

i was 15 when i made this issue and i knew practically nothing about computers and i just wanted to be that mr.robot wannabe that does illegal stuff

i am 18 years old now, went to tech school and learnt a lot more and do not want to go back to that phase ever again.

when i re-read my issue i do realize that i sound extremely stupid and i apologize.

best regards,

4lpn.

**Comment by ra1nb0rn** [comment]
Hi, no worries. It's good to hear you stuck with it and will keep on learning.
